"""Document Creator Agent — structured document generation.

Different from Draft agent: this agent focuses on filling templates,
creating formatted documents (RTI, consumer complaints, rent agreements),
and producing downloadable documents.
"""

import json
from typing import Any

from langchain_core.runnables import RunnableConfig

from agents.base import (
    AgentState,
    latest_user_text,
    register_agent,
    to_lc_messages,
)

_llm_cache: dict[str, Any] = {}

DOC_CREATOR_SYSTEM = """You are the Document Creator agent of a legal AI system.
You create structured, formatted legal documents from user requirements.

You specialise in:
- RTI Applications
- Consumer Forum Complaints
- Rent/Lease Agreements
- Legal Notices (formal format)
- Affidavits
- Power of Attorney
- Employment Contracts

Guidelines:
- Create a properly formatted, structured document.
- Use standard legal formatting with appropriate headings and sections.
- Include all mandatory fields for the document type.
- Use [PLACEHOLDER] markers for information the user hasn't provided.
- Add a header with document type and date placeholder.
- End with signature blocks where appropriate.
- Add footer: "Generated by Legal AI Assistant — Review before use."
- After the document, list what information the user still needs to fill in."""


def _get_llm(api_key: str, model: str):
    cache_key = f"doccr:{model}"
    if cache_key not in _llm_cache:
        from agents.base import get_llm
        _llm_cache[cache_key] = get_llm(api_key, model, temperature=0.3)
    return _llm_cache[cache_key]


def document_creator_generate(state: AgentState, config: RunnableConfig) -> dict[str, Any]:
    """Generate a structured legal document."""
    api_key = config.get("configurable", {}).get("api_key", "")
    model = config.get("configurable", {}).get("model", "llama-3.3-70b-versatile")

    analysis = state.get("analysis") or {}
    system = DOC_CREATOR_SYSTEM

    if analysis:
        system += (
            f"\n\nDocument request:\n"
            f"- domain: {analysis.get('domain', 'general')}\n"
            f"- jurisdiction: {analysis.get('jurisdiction', 'unspecified')}\n"
            f"- summary: {analysis.get('summary', '')}"
        )

    notes = (state.get("memory_notes") or "").strip()
    if notes:
        system += "\n\nUser context:\n" + notes

    rag = (state.get("rag_notes") or "").strip()
    if rag:
        system += "\n\nReference documents:\n" + rag

    # Use template connector for base structure
    try:
        from connectors.legal_templates import LegalTemplatesConnector
        tpl_conn = LegalTemplatesConnector()
        templates = tpl_conn.list_templates()
        if templates.get("templates"):
            tpl_names = [t["id"] for t in templates["templates"]]
            system += f"\n\nAvailable template IDs: {tpl_names}"
    except Exception:
        pass

    llm = _get_llm(api_key, model)
    result = llm.invoke(
        to_lc_messages(state.get("messages") or [], system),
        config=config,
    )
    reply = str(result.content or "").strip()

    return {
        "reply": reply,
        "active_agent": "document_creator",
        "agent_metadata": {
            "document_creator": {
                "model": model,
                "format": "structured_document",
                "disclaimer": "AI-generated document — review by a qualified lawyer recommended.",
            }
        },
    }


register_agent(
    "document_creator",
    description="Structured document creation — RTI, complaints, agreements, notices",
    handles=["document"],
)
