"""Document Creator Agent — structured document generation (agentic).

Different from Draft agent: this agent focuses on filling templates,
creating formatted documents (RTI, consumer complaints, rent agreements),
and producing downloadable documents.

Agentic pattern: template tools are bound to the LLM — it lists and
fetches the matching template itself before building the document.
"""

import logging
from typing import Any

from langchain_core.runnables import RunnableConfig

from agents.tool_loop_runner import run_agent_with_tools
from agents.base import (
    AgentState,
    register_agent,
)
from agents.agent_tools import TEMPLATE_TOOLS

logger = logging.getLogger("legal_assist.agents.document_creator")

DOC_CREATOR_SYSTEM = """You are the Document Creator agent of a legal AI system.
You create structured, formatted legal documents from user requirements.

You specialise in:
- RTI Applications
- Consumer Forum Complaints
- Rent/Lease Agreements
- Legal Notices (formal format)
- Affidavits
- Power of Attorney
- Employment Contracts

Tools: you have template tools bound to you:
- list_legal_templates: discover available templates and their ids.
- get_legal_template: fetch a template's structure and required fields.
When the requested document matches a template (RTI, consumer complaint,
rent agreement, legal notice), fetch it FIRST and build the document
on top of its structure and fields.

Guidelines:
- Create a properly formatted, structured document.
- Use standard legal formatting with appropriate headings and sections.
- Include all mandatory fields for the document type.
- Use [PLACEHOLDER] markers for information the user hasn't provided.
- Add a header with document type and date placeholder.
- End with signature blocks where appropriate.
- Add footer: "Generated by Legal AI Assistant — Review before use."
- After the document, list what information the user still needs to fill in."""


def document_creator_generate(state: AgentState, config: RunnableConfig) -> dict[str, Any]:
    """Generate a structured legal document (agentic tool loop)."""
    logger.info("document_creator_generate invoked (tools=%s)", [t.name for t in TEMPLATE_TOOLS])
    analysis = state.get("analysis") or {}
    system = DOC_CREATOR_SYSTEM

    if analysis:
        system += (
            f"\n\nDocument request:\n"
            f"- domain: {analysis.get('domain', 'general')}\n"
            f"- jurisdiction: {analysis.get('jurisdiction', 'unspecified')}\n"
            f"- summary: {analysis.get('summary', '')}"
        )

    # Inject user profile
    profile = (state.get("user_profile") or "").strip()
    if profile:
        system += "\n\nUser profile (fill in placeholders):\n" + profile

    # Inject episodic memory
    episodic = (state.get("episodic_notes") or "").strip()
    if episodic:
        system += "\n\nPast conversations:\n" + episodic

    # Inject procedural memory
    procedural = (state.get("procedural_notes") or "").strip()
    if procedural:
        system += "\n\nUser preferences:\n" + procedural

    notes = (state.get("memory_notes") or "").strip()
    if notes:
        system += "\n\nUser context:\n" + notes

    rag = (state.get("rag_notes") or "").strip()
    if rag:
        system += "\n\nReference documents:\n" + rag

    result = run_agent_with_tools(
        system,
        state.get("messages") or [],
        TEMPLATE_TOOLS,
        config,
        temperature=0.3,
    )

    return {
        "reply": result["reply"],
        "active_agent": "document_creator",
        "agent_metadata": {
            "document_creator": {
                "model": result["model"],
                "agentic": result["agentic"],
                "tools_used": [t["tool"] for t in result["tool_trace"]],
                "format": "structured_document",
                "disclaimer": "AI-generated document — review by a qualified lawyer recommended.",
            }
        },
    }


register_agent(
    "document_creator",
    description="Structured document creation — RTI, complaints, agreements, notices",
    handles=["document"],
)
